### ISSUE TITLE
Create .tailor.yml configuration file infrastructure

### ISSUE THREAD

**Issue by adityatrivedi** [sleekbyte/tailor#203]
- [x] Handle parsing of `.tailor.yml` file

Allow users to
- [x] ignore certain directories/files through `exclude`
- [x] lint specific directories/files through `include`
- [x] specify a specific `.tailor.yml` via `--config` CLI option
- [x] get the list of files that will be analyzed via `--list-files`

Example:
```yaml
include:
  - Source
exclude:
  - '**/*Test.swift'
  - '**/Carthage'
  - Pods
```
