### ISSUE TITLE
example config file

### ISSUE THREAD

**Issue by tychop** [sleekbyte/tailor#359]
We need examples on how to work with config files

**Comment by alykhank** [comment]
Hi @tychop, could you please be a bit more specific as to what you are looking for? Could you suggest something that could be added to the Configuration section of the README? https://github.com/sleekbyte/tailor#configuration

**Comment by tychop** [comment]
Sure: 
I can't get tailor to use a config file.
We want to use a config file so we can share the file amongst teams & CI servers.
It would be great if the project supplied an example file with some rules enabled and some disabled.
A small code fragment on how to feed the file to tailor would also fit nicely in the README

**Comment by alykhank** [comment]
To specify a configuration file, you may use the `--config` command-line option as follows:
```
$ tailor --config path/to/config/.tailor.yml
```

It seems as though this was a bit hard to find in our current documentation, so we'll improve the discoverability of the option and add some more examples. Hope that helps!

**Comment by tychop** [comment]
I was hoping on an example tailor.yml file as well ....

**Comment by alykhank** [comment]
We'll add some full examples to the docs, here are some samples to get you started:
```yaml
include:
    - Source            # Inspect all Swift files under "Source/"
exclude:
    - '**Tests.swift'   # Ignore Swift files that end in "Tests"
    - Source/Carthage   # Ignore Swift files under "Source/Carthage/"
    - Source/Pods       # Ignore Swift files under "Source/Pods/"
# Tailor will solely check for violations to the following rules (rule whitelist)
only:
    - upper-camel-case
    - trailing-closure
    - forced-type-cast
    - redundant-parentheses
```
```yaml
# Tailor will check for violations to all rules except for the following ones (rule blacklist)
except:
    - parenthesis-whitespace
    - lower-camel-case
```
